#datasource config
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://pg.cx7tmt6mbnem.eu-west-2.rds.amazonaws.com:5432/mountain-spring
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

#spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.jdbc.batch_size=30
spring.jpa.properties.hibernate.order_inserts=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_KBRPYdyOP